### PR TITLE
Create 1-challenge-ai-risingstars.md

### PR DESCRIPTION
**Pull request by Vaibhavpratapsingh22**
Challenge -1 created 
# 🏎️

### CODE REVIEW

**Review by udeysingh95 — CHANGES_REQUESTED** [review]
This is very cool - did you make it yourself? 
But this is not the top item in rising stars logos on the website. 

you can find the challenge logo here - https://graphicriver.net/item/bird-logo/28418226

**Comment by Vaibhavpratapsingh22** [comment]
Yes, I have made that.
I searched for rising stars this the logo that I designed came first, so I thought this is the logo we have to design.
Okay, I will design this one 👍 No problem.

**Review by udeysingh95 — CHANGES_REQUESTED** [review]
add the reference image first - in small size and then your work - so that i can check it directly here - how close is your creation to the actual challenge.

**Comment by udeysingh95** [comment]
Text is missing in the logo

**Comment by udeysingh95** [comment]
Text part needs improvements. It's not looking nice.

**Review by udeysingh95 — CHANGES_REQUESTED** [review]
text is still not upto the mark.

**Review by udeysingh95 — APPROVED** [review]

**Pull request merged**
