### PR TITLE
OSI model

### PR DESCRIPTION
**Pull request by Vaibhavpratapsingh22**
### Chapter -3 created 🚀

### CODE REVIEW

**Review by udeysingh95 — CHANGES_REQUESTED** [review]
Very good work. 
I have a small concern - in OSI model section - you have started with Application layer - which is layer number 7 - and in our document its getting number 1 - according to how you started. 
Do you think it makes sense to start with the physical layer - so we start from the bottom of the model and then go up and data goes up. Point number will also get automatically corrected then.

**Comment by udeysingh95** [comment]
What are the sources that you used to learn about this. 
Which model did you like personally and why? 
which one of these do you think is more in use?

**Comment by Vaibhavpratapsingh22** [comment]
> Do you think it makes sense to start with the physical layer - so we start from the bottom of the model and then go up and data goes up. Point number will also get automatically corrected then.
@udeysingh95, I have we start from the bottom when we are at the receiver side and we start from the top when we are on the sender side. In this, I have discussed the sender side workflow of the model. So we start from the application layer and go down to the physical layer.

**Comment by Vaibhavpratapsingh22** [comment]
> What are the sources that you used to learn about this.

1. https://medium.com/swlh/understanding-the-osi-model-fa429397324
2.  https://www.youtube.com/watch?v=vv4y_uOneC0

> Which model did you like personally and why?

I liked both of the models as they are almost similar in structure, but I would say I enjoyed learning the OSI model. It was very interesting and I was fully focused while learning it. When I started learning the TCP/IP model mostly the language was the same.
But I know that they are very different from each other. At last, I would like to say
The tagline "OSI is a reference model whereas TCP/IP is an implementation model". 😄 

> which one of these do you think is more in use?

I will go with the OSI model, as it acts as a base of networking, through this model I understood how the data actually travelled from sender to receiver.

> Watch this video for further and deeper learning on this topic: https://www.youtube.com/watch?v=-6Uoku-M6oY

The video was very interesting mainly the way he explained the video. Thanks for the link.

**Review by udeysingh95 — APPROVED** [review]

**Pull request merged**
