### PR TITLE
Logo for organic flower shop & civic instinct

### PR DESCRIPTION
**Pull request by Vaibhavpratapsingh22**
# 🌹Organic Flower Shop logo

### CODE REVIEW

**Review by udeysingh95 — CHANGES_REQUESTED** [review]
add more styles to Civic Instinct. They are very basic designs.

**Review by udeysingh95 — CHANGES_REQUESTED** [review]
Need more work on CI logo - colors are off!!

**Review by udeysingh95 — APPROVED** [review]

**Review by udeysingh95 — CHANGES_REQUESTED** [review]
Online shopping - no no no. Read about flat designs. and always add individual PNG files - not one screenshot. Use more and more flat colors and flat designs. Its the time of flat UI.
- [ ] Here you can find colour sets: https://flatuicolors.com/
- [ ] Here you can read about flat UI design: https://uxplanet.org/best-practices-for-flat-design-6e7a6997805

**Review by udeysingh95 — CHANGES_REQUESTED** [review]
Try to implement flat designs and light weight. Logos have too much content in there - they're saying and showing and then colors are too poppy. That's old style now. 
Try to use more of creativity and soothing colors. 
Try to express rather than saying. 
And online shopping is super off!

**Review by udeysingh95 — CHANGES_REQUESTED** [review]
why is a cake shop called Fashion Hub 1? and what is this logo portraying? 
Online Shopping is still not there. 
I would say - to think from another perspective - maybe have a look at other similar logos or something from different industry and try to spice things up. The second variant is having too many things in it. 

Also, provide icons along with logos - so. your. work is future-ready for customers - they can simply get an app and use your icons - upload PNG files always and add those 4 variants of the same logo that we discussed. 
Dont rush into updating - focus on raising the quality.

**Comment by Vaibhavpratapsingh22** [comment]
@udeysingh95, that was by mistake 😄  Sure I will work on it. I am uploading PNG files only no other. Sure, will raise the quality 👍

**Review by udeysingh95 — COMMENTED** [review]
what about the cake. shop logo? 
Online shopping is looking good finally! great job!

**Comment by Vaibhavpratapsingh22** [comment]
Working on the cake shop logo 😃

**Review by udeysingh95 — CHANGES_REQUESTED** [review]
There are still too many things in the cake shop logo.

**Review by udeysingh95 — APPROVED** [review]

**Review by udeysingh95 — CHANGES_REQUESTED** [review]
Cake shop logo is coming in shape - but now it looks like donut shop and not cake shop

**Review by udeysingh95 — APPROVED** [review]

**Pull request merged**
