### PR TITLE
Create 1-challenge.c

### PR DESCRIPTION
**Pull request by Vaibhavpratapsingh22**
This code is working for the first input mentioned in the issue .Update will be uploaded in a short period.

### CODE REVIEW

**Comment by udeysingh95** [comment]
Can you post pictures of output when you are entering these values?

**Comment by udeysingh95** [comment]
I meant with output - here, in a comment only. Add images here not in repo. 
For now, there's a png file in greedy folder. We don't need that. Just in comments on this PR.

**Comment by Vaibhavpratapsingh22** [comment]
Output challenge-1

**Comment by udeysingh95** [comment]
Out of 11999 is wrong. There's no 10000rs note in India. 
Need to check it there.

**Comment by udeysingh95** [comment]
New screenshots please

**Comment by udeysingh95** [comment]
For this time - it is fine. But you have created hash.c on challenge branch. this branch was supposed to have only challenge code and updated readme. 
Next time - don't overload irrelevant stuff on one branch always. it makes it difficult to review. Because then there are too many things to review on a single branch. 
As I said - for now, it is ok. 

- [ ] add the new outputs here in comments - a picture or just copy past here - both are ok

**Comment by Vaibhavpratapsingh22** [comment]
Screenshot (2)
Screenshot (14)

**Comment by udeysingh95** [comment]
cool work. all sorted till here.

**Pull request merged**
